name: StandKnife Final Victory
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Run Build inside Unity Container
        # Этот образ открыт и доступен всегда!
        run: |
          docker run --rm \
            -v $(pwd):/project \
            unityci/editor:ubuntu-2022.3.7f1-android-3 \
            bash -c "unity-editor \
              -batchmode \
              -nographics \
              -projectPath /project \
              -buildTarget Android \
              -customBuildName StandKnife \
              -executeMethod UnityBuilder.Build \
              -quit \
              -logFile /dev/stdout" || true

      - name: Search and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: StandKnife-APK
          path: "**/*.apk"
        uses: actions/upload-artifact@v4
        with:
          name: StandKnife-Hacker-APK
          path: ./*.apk
